Date Picker 추가
transverse-dev/evoui pull request #96
Opened 2022-11-28 07:39 UTC by Kijun-Park

## Checklist before merge ✅

- [ ] PR 제목이 직관적인가요?
  - 짧고 간결하지만 명확하게 (브랜치 명 금지)
  - Jira Ticket 있을 경우 함께 남기기
- [ ] QA 검증이 완료되었나요?
  - [ ] Test 체크리스트 1
  - [ ] Test 체크리스트 2
  - [ ] …
- [ ] 코드 리뷰가 완료되었나요?

## What is this PR? 🚀

> 아래 항목 중 해당되는 항목에만 내용을 입력해 주세요.<br>
> Jira Ticket 의 경우 EVO-XX 와 해당 티켓에 링크도 걸어주세요<br>
> 만약 위 사항이 없는 간단한 PR 이라면, 해결하려는 문제만 적어주세요.

- 해결하려는 문제: Date Picker 컴포넌트 추가

## Changes 🔥

> 이번 PR 에서 변경된 내용을 적어주세요.<br>
> 예시)<br>모달에 사용자에게 더 편리한 기능을 추가합니다. <br>- 모달 자동 스크롤 기능 구현 <br>- 크게 보기 기능 구현<br>…

Date Picker 컴포넌트를 추가합니다

## Attachment 🌳

> 리뷰어들에게 이번 PR 의 이해를 도와주는 GIF, PNG 이미지 파일을 첨부해 주세요.<br>
> 만약 불필요하다 생각 되실 경우, 항목을 제거해 주세요.

## To Reviewers 🐚

> 리뷰어들에게 어떤 부분에서 리뷰를 중점적으로 해야하는지, 리뷰 시 참고사항을 적어주세요.

2022-12-01 04:14 UTC, sehvdi reviewed
코멘트 남겼습니다..!

2022-12-01 04:14 UTC, sehvdi commented on src/evoui/components/ClickAwayListener/ClickAwayListener.tsx
> +    console.dir(e.target);
P3: 테스트용 코드라면 나중에 삭제 부탁드립니다.

2022-12-01 04:14 UTC, sehvdi commented on src/evoui/components/ClickAwayListener/ClickAwayListener.tsx
> +  let listenerRef = useRef<HTMLInputElement>(null);
P4: 변하지 않는 값이라면 const로 선언 부탁드립니다.

2022-12-01 09:17 UTC, sehvdi requested changes
코드를 정말 깔끔하게 잘 작성하신 것 같습니다..! 특히 함수 분리를 잘해주셔서 그런지 리뷰하기 편했습니다ㅎㅎ 코멘트 확인해주시고 마무리 작업 부탁드립니다!!

2022-12-01 09:17 UTC, puppywimy commented on src/evoui/components/DatePicker/datePicker.tsx
> +  };
P3: handleCalendarVisible은 setCalendarVisible(true)가 맞을까요?

2022-12-01 09:17 UTC, puppywimy commented on src/evoui/components/DatePicker/datePicker.tsx
> +          : selectedStartDate.getMonth() + 1;
P5: `` `0${selectedStartDate.getMonth() + 1}`.slice(-2)``하면 깔끔할 것 같습니다:)

2022-12-01 09:17 UTC, puppywimy commented on src/evoui/components/DatePicker/datePicker.tsx
> +      const day = selectedStartDate.getDate();
P2: 위에는 0을 앞에 추가해주셔서 day도 추가해주시는 것이 통일성 있을 것 같습니다.

2022-12-01 09:17 UTC, puppywimy commented on src/evoui/components/DatePicker/datePicker.tsx
> +  };
P2: renderStartDate와 같은 이슈입니다~

2022-12-01 09:17 UTC, puppywimy commented on src/evoui/components/DatePicker/datePicker.tsx
> +    newDate.setMonth(Number(months[currentMonth].id) - 1);
P5: id가 외부에 보이는 값이 아니라면 0~11로 설계하는 것이 개발할 때 편할 것 같기도 합니다:)

2022-12-01 09:17 UTC, puppywimy commented on src/evoui/components/DatePicker/datePicker.tsx
> +    newDate.setDate(Number(day));
P5: day가 이미 number 타입인데 형변환 하신 이유가 무엇인가요?

2022-12-01 09:17 UTC, puppywimy commented on src/evoui/components/DatePicker/datePicker.tsx
> +  };
P5: 위와 동일한 이슈입니다~

2022-12-01 09:17 UTC, puppywimy commented on src/evoui/components/DatePicker/datePicker.tsx
> +      years.findIndex((item: ItemType) => item.id === selected.id),
P3: 요거를 findIndex로 처리하신 이유가 있으신가요? `setCurrentYear(selected.id - 1)`만 사용하면 어떻게 되나요?

2022-12-01 09:17 UTC, sehvdi commented on src/evoui/components/DatePicker/datePicker.tsx
> +                    stroke-width='2.5'
P5: 요거 오류나면 strokeWidth로 바꿔주세요. (다른 props도)

2022-12-06 06:14 UTC, Kijun-Park commented on src/evoui/components/DatePicker/datePicker.tsx
> +  };
날짜를 눌렀을떄 달력이 켜져있으면 꺼지고 꺼져있으면 켜져야 할거같아서 setCalendarVisible(!calendarVisible) 요렇게 했습니다!

2022-12-06 06:20 UTC, Kijun-Park commented on src/evoui/components/DatePicker/datePicker.tsx
> +    newDate.setDate(Number(day));
엇 원래 day가 string이였는데 number로 바꾸면서 저부분이 수정이 안된거같습니다!

2022-12-06 06:23 UTC, Kijun-Park commented on src/evoui/components/DatePicker/datePicker.tsx
> +      years.findIndex((item: ItemType) => item.id === selected.id),
currentYear랑 currentMonth는 years랑, months 배열의 인덱스를 가르키는 애라서 저렇게 작성했습니다!

2022-12-06 06:48 UTC, sehvdi commented on src/evoui/components/DatePicker/datePicker.tsx
> +  };
아하 handleCalendarInvisible과 나란히 있어 헷갈렸던 것 같습니다. 감사합니다:)

P5: 개인적으로 아래와 같은 함수명이 더 명확해보이는 것 같습니다.
handleCalendarVisible -> toggleCalendarVisibility
handleCalendarInvisible -> setCalendarInvisible

2022-12-06 06:57 UTC, sehvdi commented on src/evoui/components/DatePicker/datePicker.tsx
> +      years.findIndex((item: ItemType) => item.id === selected.id),
P3: years와 months 배열에서 각각의 item id들은 item을 구별하기 위한 목적으로 할당하는 것이어서 인덱스보다 id를 사용하는 것이 깔끔하지 않을까요?

2022-12-06 07:01 UTC, sehvdi approved these changes
LGTM

2022-12-07 07:14 UTC, merged